name = "esp_idf"
description = "Ada bindings for the ESP-IDF"
version = "5.0.3-1"

authors = ["Johannes Kliemann"]
maintainers = ["Johannes Kliemann <jk@jkliemann.de>"]
maintainers-logins = ["jklmnn"]
[[depends-on]]
hal = "~0.3.0"
