name: Build

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: alire-project/setup-alire@v2
    - name: Build
      run: alr build
